// AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// CURRENCY CONVERSION
export const GET_ALL_RATES = 'GET_ALL_RATES';
export const GET_UPATED_RATE = 'GET_UPATED_RATE'